### ISSUE TITLE
Job is stopping after a long period of time

### ISSUE THREAD

**Issue by mguegnol** [sankalpjonn/timeloop#12]
Hi ! It seems that after a long period of time, the Job is stopping by itself as shown in the first line of trace. Any idea why ? 
Thank's !

```
[2019-12-09 06:25:25,145] [timeloop] [INFO] Stopping job <function hourly_routine_check at 0x7f652dfb6dc0>
Traceback (most recent call last):
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/app.py", line 33, in _block_main_thread
    time.sleep(1)
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/helpers.py", line 5, in service_shutdown
    raise ServiceExit
timeloop.exceptions.ServiceExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xx/file.py", line 153, in <module>
    tl.start(block=True)
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/app.py", line 65, in start
    self._block_main_thread()
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/app.py", line 35, in _block_main_thread
    self.stop()
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/app.py", line 56, in stop
    self._stop_jobs()
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/app.py", line 47, in _stop_jobs
    j.stop()
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/job.py", line 15, in stop
    self.join()
  File "/usr/xx/python/3.8.0/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/xx/python/3.8.0/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/helpers.py", line 5, in service_shutdown
    raise ServiceExit
timeloop.exceptions.ServiceExit



Exception ignored in: <module 'threading' from '/usr/xx/python/3.8.0/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/xx/python/3.8.0/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
  File "/home/xx/.local/lib/python3.8/site-packages/timeloop/helpers.py", line 5, in service_shutdown
    raise ServiceExit
timeloop.exceptions.ServiceExit:
```

**Comment by guilhermesperb** [comment]
Did you find the solution?
